from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 811, 471))
        self.tabWidget.setMinimumSize(QtCore.QSize(771, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.label_2 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_2.setGeometry(QtCore.QRect(220, 10, 471, 61))
        self.label_2.setStyleSheet("font: 75 36pt \"Comic Sans\";")
        self.label_2.setObjectName("label_2")
        self.btnAgregaA = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.btnAgregaA.setGeometry(QtCore.QRect(350, 380, 75, 23))
        self.btnAgregaA.setObjectName("btnAgregaA")
        self.layoutWidget = QtWidgets.QWidget(self.tabWidgetPage1)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 110, 331, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.txtRaza = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtRaza.setObjectName("txtRaza")
        self.gridLayout_3.addWidget(self.txtRaza, 2, 1, 1, 1)
        self.txtEspecie = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtEspecie.setObjectName("txtEspecie")
        self.gridLayout_3.addWidget(self.txtEspecie, 1, 1, 1, 1)
        self.txtNombre = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtNombre.setObjectName("txtNombre")
        self.gridLayout_3.addWidget(self.txtNombre, 0, 1, 1, 1)
        self.txtEdad = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtEdad.setObjectName("txtEdad")
        self.gridLayout_3.addWidget(self.txtEdad, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 5, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.rdbAlta = QtWidgets.QRadioButton(self.layoutWidget)
        self.rdbAlta.setObjectName("rdbAlta")
        self.gridLayout.addWidget(self.rdbAlta, 0, 0, 1, 1)
        self.rdbRecuperacion = QtWidgets.QRadioButton(self.layoutWidget)
        self.rdbRecuperacion.setObjectName("rdbRecuperacion")
        self.gridLayout.addWidget(self.rdbRecuperacion, 0, 1, 1, 1)
        self.rdbCritico = QtWidgets.QRadioButton(self.layoutWidget)
        self.rdbCritico.setObjectName("rdbCritico")
        self.gridLayout.addWidget(self.rdbCritico, 1, 1, 1, 1)
        self.rdbTratamiento = QtWidgets.QRadioButton(self.layoutWidget)
        self.rdbTratamiento.setObjectName("rdbTratamiento")
        self.gridLayout.addWidget(self.rdbTratamiento, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 4, 1, 1, 1)
        self.cbxDuenio = QtWidgets.QComboBox(self.layoutWidget)
        self.cbxDuenio.setObjectName("cbxDuenio")
        self.gridLayout_3.addWidget(self.cbxDuenio, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.splitter = QtWidgets.QSplitter(self.tabWidgetPage2)
        self.splitter.setGeometry(QtCore.QRect(280, 140, 156, 35))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.btnEliminaE = QtWidgets.QPushButton(self.tabWidgetPage2)
        self.btnEliminaE.setGeometry(QtCore.QRect(470, 410, 75, 23))
        self.btnEliminaE.setObjectName("btnEliminaE")
        self.label_9 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.label_9.setGeometry(QtCore.QRect(210, 10, 481, 71))
        self.label_9.setStyleSheet("font: 75 36pt \"Comic Sans\";")
        self.label_9.setObjectName("label_9")
        self.tblEliminar = QtWidgets.QTableWidget(self.tabWidgetPage2)
        self.tblEliminar.setGeometry(QtCore.QRect(0, 90, 801, 301))
        self.tblEliminar.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblEliminar.setObjectName("tblEliminar")
        self.tblEliminar.setColumnCount(8)
        self.tblEliminar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tblEliminar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEliminar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEliminar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEliminar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEliminar.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEliminar.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEliminar.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tblEliminar.setHorizontalHeaderItem(7, item)
        self.label_17 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.label_17.setGeometry(QtCore.QRect(210, 410, 111, 20))
        self.label_17.setObjectName("label_17")
        self.txtIDEliminar = QtWidgets.QLineEdit(self.tabWidgetPage2)
        self.txtIDEliminar.setGeometry(QtCore.QRect(330, 410, 113, 20))
        self.txtIDEliminar.setObjectName("txtIDEliminar")
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tabWidgetPage3 = QtWidgets.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.label_10 = QtWidgets.QLabel(self.tabWidgetPage3)
        self.label_10.setGeometry(QtCore.QRect(270, 70, 191, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tabWidgetPage3)
        self.label_11.setGeometry(QtCore.QRect(160, 10, 551, 51))
        self.label_11.setStyleSheet("font: 75 36pt \"Comic Sans\";")
        self.label_11.setObjectName("label_11")
        self.txtIDMascUp = QtWidgets.QLineEdit(self.tabWidgetPage3)
        self.txtIDMascUp.setGeometry(QtCore.QRect(290, 100, 113, 20))
        self.txtIDMascUp.setObjectName("txtIDMascUp")
        self.btnBuscarUp = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.btnBuscarUp.setGeometry(QtCore.QRect(430, 100, 75, 23))
        self.btnBuscarUp.setObjectName("btnBuscarUp")
        self.label_12 = QtWidgets.QLabel(self.tabWidgetPage3)
        self.label_12.setGeometry(QtCore.QRect(260, 100, 21, 21))
        self.label_12.setObjectName("label_12")
        self.btnActualizar = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.btnActualizar.setGeometry(QtCore.QRect(330, 350, 75, 23))
        self.btnActualizar.setObjectName("btnActualizar")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tabWidgetPage3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(220, 150, 311, 174))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.txtNombreUp = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.txtNombreUp.setObjectName("txtNombreUp")
        self.gridLayout_4.addWidget(self.txtNombreUp, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.txtEspecieUp = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.txtEspecieUp.setObjectName("txtEspecieUp")
        self.gridLayout_4.addWidget(self.txtEspecieUp, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 1)
        self.txtRazaUp = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.txtRazaUp.setObjectName("txtRazaUp")
        self.gridLayout_4.addWidget(self.txtRazaUp, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1)
        self.txtEdadUp = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.txtEdadUp.setObjectName("txtEdadUp")
        self.gridLayout_4.addWidget(self.txtEdadUp, 3, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 4, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rdbAltaUp = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.rdbAltaUp.setObjectName("rdbAltaUp")
        self.gridLayout_2.addWidget(self.rdbAltaUp, 0, 0, 1, 1)
        self.rdbRecuperacionUp = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.rdbRecuperacionUp.setObjectName("rdbRecuperacionUp")
        self.gridLayout_2.addWidget(self.rdbRecuperacionUp, 0, 1, 1, 1)
        self.rdbCriticoUp = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.rdbCriticoUp.setObjectName("rdbCriticoUp")
        self.gridLayout_2.addWidget(self.rdbCriticoUp, 1, 1, 1, 1)
        self.rdbTratamientoUp = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.rdbTratamientoUp.setObjectName("rdbTratamientoUp")
        self.gridLayout_2.addWidget(self.rdbTratamientoUp, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 4, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 5, 0, 1, 1)
        self.cbxDuenioUp = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cbxDuenioUp.setObjectName("cbxDuenioUp")
        self.gridLayout_4.addWidget(self.cbxDuenioUp, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage3, "")
        self.tabWidgetPage4 = QtWidgets.QWidget()
        self.tabWidgetPage4.setObjectName("tabWidgetPage4")
        self.label_13 = QtWidgets.QLabel(self.tabWidgetPage4)
        self.label_13.setGeometry(QtCore.QRect(300, 10, 391, 71))
        self.label_13.setStyleSheet("font: 75 36pt \"Comic Sans\";")
        self.label_13.setObjectName("label_13")
        self.txtIDMascCon = QtWidgets.QLineEdit(self.tabWidgetPage4)
        self.txtIDMascCon.setGeometry(QtCore.QRect(170, 80, 113, 20))
        self.txtIDMascCon.setObjectName("txtIDMascCon")
        self.label_18 = QtWidgets.QLabel(self.tabWidgetPage4)
        self.label_18.setGeometry(QtCore.QRect(80, 80, 71, 16))
        self.label_18.setObjectName("label_18")
        self.btnBuscarCon = QtWidgets.QPushButton(self.tabWidgetPage4)
        self.btnBuscarCon.setGeometry(QtCore.QRect(300, 80, 75, 23))
        self.btnBuscarCon.setObjectName("btnBuscarCon")
        self.tblConsultar = QtWidgets.QTableWidget(self.tabWidgetPage4)
        self.tblConsultar.setGeometry(QtCore.QRect(10, 110, 771, 291))
        self.tblConsultar.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblConsultar.setObjectName("tblConsultar")
        self.tblConsultar.setColumnCount(8)
        self.tblConsultar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tblConsultar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultar.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultar.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConsultar.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tblConsultar.setHorizontalHeaderItem(7, item)
        self.tabWidget.addTab(self.tabWidgetPage4, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-4, 0, 801, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("background-color:rgb(0, 49, 97);\n"
"font: 75 16pt \"Verdana\";\n"
"color: white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btnRegresar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegresar.setGeometry(QtCore.QRect(350, 530, 91, 23))
        self.btnRegresar.setObjectName("btnRegresar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Agregar Mascota"))
        self.btnAgregaA.setText(_translate("MainWindow", "Añadir"))
        self.label_7.setText(_translate("MainWindow", "Edad:"))
        self.label_3.setText(_translate("MainWindow", "Nombre:"))
        self.label_5.setText(_translate("MainWindow", "Especie:"))
        self.label_4.setText(_translate("MainWindow", "Raza:"))
        self.label_19.setText(_translate("MainWindow", "Estado:"))
        self.label_20.setText(_translate("MainWindow", "Dueño:"))
        self.rdbAlta.setText(_translate("MainWindow", "Alta"))
        self.rdbRecuperacion.setText(_translate("MainWindow", "Recuperación"))
        self.rdbCritico.setText(_translate("MainWindow", "Crítico"))
        self.rdbTratamiento.setText(_translate("MainWindow", "Tratamiento"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "Añadir"))
        self.btnEliminaE.setText(_translate("MainWindow", "Eliminar"))
        self.label_9.setText(_translate("MainWindow", "Eliminar Mascota"))
        item = self.tblEliminar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID  Mascota"))
        item = self.tblEliminar.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tblEliminar.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Especie"))
        item = self.tblEliminar.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Raza"))
        item = self.tblEliminar.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Edad"))
        item = self.tblEliminar.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Estado"))
        item = self.tblEliminar.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ID Dueño"))
        item = self.tblEliminar.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Nombre Dueño"))
        self.label_17.setText(_translate("MainWindow", "Ingrese ID a eliminar:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWindow", "Eliminar"))
        self.label_10.setText(_translate("MainWindow", "Ingrese ID de la  mascota actualizar"))
        self.label_11.setText(_translate("MainWindow", "Actualizar  Mascota"))
        self.btnBuscarUp.setText(_translate("MainWindow", "Buscar"))
        self.label_12.setText(_translate("MainWindow", "ID"))
        self.btnActualizar.setText(_translate("MainWindow", "Actualizar"))
        self.label_15.setText(_translate("MainWindow", "Nombre:"))
        self.label_14.setText(_translate("MainWindow", "Especie:"))
        self.label_16.setText(_translate("MainWindow", "Raza:"))
        self.label_8.setText(_translate("MainWindow", "Edad:"))
        self.label_21.setText(_translate("MainWindow", "Estado:"))
        self.rdbAltaUp.setText(_translate("MainWindow", "Alta"))
        self.rdbRecuperacionUp.setText(_translate("MainWindow", "Recuperación"))
        self.rdbCriticoUp.setText(_translate("MainWindow", "Crítico"))
        self.rdbTratamientoUp.setText(_translate("MainWindow", "Tratamiento"))
        self.label_22.setText(_translate("MainWindow", "Dueño:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("MainWindow", "Actualizar"))
        self.label_13.setText(_translate("MainWindow", " Mascotas"))
        self.label_18.setText(_translate("MainWindow", "Ingrese ID:"))
        self.btnBuscarCon.setText(_translate("MainWindow", "Buscar"))
        item = self.tblConsultar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID  Mascota"))
        item = self.tblConsultar.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tblConsultar.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Especie"))
        item = self.tblConsultar.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Raza"))
        item = self.tblConsultar.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Edad"))
        item = self.tblConsultar.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Estado"))
        item = self.tblConsultar.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ID Dueño"))
        item = self.tblConsultar.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Nombre Dueño"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage4), _translate("MainWindow", "Consultar"))
        self.label.setText(_translate("MainWindow", "Mascotas"))
        self.btnRegresar.setText(_translate("MainWindow", "Volver al Menú"))
