from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTitulo.setGeometry(QtCore.QRect(240, 10, 331, 81))
        self.lblTitulo.setStyleSheet("font: 36pt \"Verdana\";")
        self.lblTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")
        self.lblImg = QtWidgets.QLabel(self.centralwidget)
        self.lblImg.setGeometry(QtCore.QRect(320, 90, 151, 121))
        self.lblImg.setText("")
        self.lblImg.setPixmap(QtGui.QPixmap("imgenes/log.png"))
        self.lblImg.setScaledContents(True)
        self.lblImg.setObjectName("lblImg")
        self.lblUser = QtWidgets.QLabel(self.centralwidget)
        self.lblUser.setGeometry(QtCore.QRect(290, 240, 47, 13))
        self.lblUser.setObjectName("lblUser")
        self.lblContrasenia = QtWidgets.QLabel(self.centralwidget)
        self.lblContrasenia.setGeometry(QtCore.QRect(290, 310, 71, 16))
        self.lblContrasenia.setObjectName("lblContrasenia")
        self.txtUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUsuario.setGeometry(QtCore.QRect(400, 240, 113, 20))
        self.txtUsuario.setObjectName("txtUsuario")
        self.txtContrasenia = QtWidgets.QLineEdit(self.centralwidget)
        self.txtContrasenia.setGeometry(QtCore.QRect(400, 300, 113, 20))
        self.txtContrasenia.setObjectName("txtContrasenia")
        self.btnIngresar = QtWidgets.QPushButton(self.centralwidget)
        self.btnIngresar.setGeometry(QtCore.QRect(290, 390, 75, 23))
        self.btnIngresar.setObjectName("btnIngresar")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(430, 390, 75, 23))
        self.btnSalir.setObjectName("btnSalir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTitulo.setText(_translate("MainWindow", "¡Bienvenido!"))
        self.lblUser.setText(_translate("MainWindow", "Usuario:"))
        self.lblContrasenia.setText(_translate("MainWindow", "Contraseña:"))
        self.btnIngresar.setText(_translate("MainWindow", "Ingresar"))
        self.btnSalir.setText(_translate("MainWindow", "Salir"))
